{{- if and (.Values.rbac).enabled .Values.rbac.roles }}
{{- range .Values.rbac.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "application.name" $ }}-rolebinding-{{ .name }}
  namespace: {{ template "application.namespace" $ }}
  {{- with (mergeOverwrite $.Values.global.annotations $.Values.rbac.serviceAccount.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "terrateam.labels" $ | nindent 4 }}
    {{- with (mergeOverwrite $.Values.global.labels $.Values.rbac.serviceAccount.labels) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "application.name" $ }}-role-{{ .name }}
subjects:
  - kind: ServiceAccount
  {{- if $.Values.rbac.serviceAccount.name }}
    name: {{ $.Values.rbac.serviceAccount.name }}
  {{- else }}
    name: {{ template "application.name" $ }}
  {{- end }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
