{{- if and .Values.rbac.enabled .Values.rbac.serviceAccount.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "application.name" .) .Values.rbac.serviceAccount.name }}
  namespace: {{ template "application.namespace" . }}
  {{- with (mergeOverwrite .Values.global.annotations .Values.rbac.serviceAccount.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "terrateam.labels" $ | nindent 4 }}
    {{- with (mergeOverwrite .Values.global.labels .Values.rbac.serviceAccount.labels) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
